# Production 1
Production.create(:name=>"Awesome Line")

# producers
User.create(:production_id=>1, :first_name=>"Edgar", :last_name=>"Norris", :email=>"producer1@1.com" ,:password=>"12345678", :phone_number=>"0541119111", :role=>"producer", :lock=>false)
User.create(:production_id=>1, :first_name=>"Jony", :last_name=>"Beck", :email=>"producer2@1.com" ,:password=>"12345678", :phone_number=>"0541111112", :role=>"producer", :lock=>false)

# promoters
User.create(:production_id=>1, :first_name=>"Harmonie", :last_name=>"Diane", :email=>"promoter1@1.com" ,:password=>"12345678", :role=>"promoter", :lock=>false)
User.create(:production_id=>1, :first_name=>"Diana", :last_name=>"Burke", :email=>"promoter2@1.com" ,:password=>"12345678", :role=>"promoter", :lock=>false)
User.create(:production_id=>1, :first_name=>"Melanie", :last_name=>"Jensen", :email=>"promoter3@1.com" ,:password=>"12345678", :role=>"promoter", :lock=>false)
User.create(:production_id=>1, :first_name=>"Cathy", :last_name=>"Daniel", :email=>"promoter4@1.com" ,:password=>"12345678", :role=>"promoter", :lock=>false)
User.create(:production_id=>1, :first_name=>"Eva", :last_name=>"Robbins", :email=>"promoter5@1.com" ,:password=>"12345678", :role=>"promoter", :lock=>false)

# cashiers
User.create(:production_id=>1, :first_name=>"Victoria", :last_name=>"Watson", :email=>"cashier1@1.com" ,:password=>"12345678", :role=>"cashier", :lock=>false)
User.create(:production_id=>1, :first_name=>"Orville", :last_name=>"Burke", :email=>"cashier2@1.com" ,:password=>"12345678", :role=>"cashier", :lock=>false)
User.create(:production_id=>1, :first_name=>"Bert", :last_name=>"Manning", :email=>"cashier3@1.com" ,:password=>"12345678", :role=>"cashier", :lock=>false)

# lock users
User.create(:production_id=>1, :first_name=>"Troy", :last_name=>"Pope", :email=>"lock1@1.com" ,:password=>"12345678", :phone_number=>"0541211111", :role=>"producer", :lock=>true)
User.create(:production_id=>1, :first_name=>"Rose", :last_name=>"Harper", :email=>"lock2@1.com" ,:password=>"12345678", :phone_number=>"0544111111", :role=>"promoter", :lock=>true)
User.create(:production_id=>1, :first_name=>"Shari", :last_name=>"Scott", :email=>"lock3@1.com" ,:password=>"12345678", :phone_number=>"0541111111", :role=>"cashier", :lock=>true)

# clients
Client.create(:production_id=>1 ,:first_name=>"Alex", :last_name=>"Hunt", :gender=>"male", :phone_number=>"0501111111", :city =>"Tel Mond", :birthdate=>"1997-05-21")
Client.create(:production_id=>1 ,:first_name=>"Leland", :last_name=>"Willis", :gender=>"male", :phone_number=>"0502111111", :city =>"Tel Mond", :birthdate=>"1997-05-22")
Client.create(:production_id=>1 ,:first_name=>"Luther", :last_name=>"Barnes", :gender=>"male", :phone_number=>"0503111111", :city =>"Tel Mond", :birthdate=>"1997-05-23")
Client.create(:production_id=>1 ,:first_name=>"Donnie", :last_name=>"Hill", :gender=>"male", :phone_number=>"0504111111", :city =>"Tel Mond", :birthdate=>"1997-05-24")
Client.create(:production_id=>1 ,:first_name=>"Christopher", :last_name=>"Mann", :gender=>"male", :phone_number=>"0505111111", :city =>"Tel Mond", :birthdate=>"1997-05-25")
Client.create(:production_id=>1 ,:first_name=>"Paul", :last_name=>"Mccarthy", :gender=>"male", :phone_number=>"0506111111", :city =>"Tel Mond", :birthdate=>"1997-05-26")
Client.create(:production_id=>1 ,:first_name=>"Bob", :last_name=>"Valdez", :gender=>"male", :phone_number=>"0507111111", :city =>"Tel Mond", :birthdate=>"1997-05-27")
Client.create(:production_id=>1 ,:first_name=>"Robin", :last_name=>"Neal", :gender=>"male", :phone_number=>"0508111111", :city =>"Tel Mond", :birthdate=>"1997-05-28")
Client.create(:production_id=>1 ,:first_name=>"Dana", :last_name=>"Parks", :gender=>"male", :phone_number=>"0509111111", :city =>"Tel Mond", :birthdate=>"1997-05-29")
Client.create(:production_id=>1 ,:first_name=>"Sam", :last_name=>"Gilbert", :gender=>"male", :phone_number=>"0500111111", :city =>"Tel Mond", :birthdate=>"1997-05-80")
Client.create(:production_id=>1 ,:first_name=>"Ted", :last_name=>"Wilkins", :gender=>"male", :phone_number=>"0501111111", :city =>"Tel Aviv", :birthdate=>"1997-06-21")
Client.create(:production_id=>1 ,:first_name=>"Rene", :last_name=>"Frazier", :gender=>"male", :phone_number=>"0501211111", :city =>"Tel Aviv", :birthdate=>"1997-06-22")
Client.create(:production_id=>1 ,:first_name=>"Darin", :last_name=>"Daniels", :gender=>"male", :phone_number=>"0501311111", :city =>"Tel Aviv", :birthdate=>"1997-06-23")
Client.create(:production_id=>1 ,:first_name=>"Phillip", :last_name=>"Cummings", :gender=>"male", :phone_number=>"0501411111", :city =>"Tel Aviv", :birthdate=>"1997-06-24")
Client.create(:production_id=>1 ,:first_name=>"Marcus", :last_name=>"Austin", :gender=>"male", :phone_number=>"0501511111", :city =>"Tel Aviv", :birthdate=>"1997-06-25")
Client.create(:production_id=>1 ,:first_name=>"Hector", :last_name=>"Sparks", :gender=>"male", :phone_number=>"0501611111", :city =>"Tel Aviv", :birthdate=>"1997-06-26")
Client.create(:production_id=>1 ,:first_name=>"Fredrick", :last_name=>"Grant", :gender=>"male", :phone_number=>"0501711111", :city =>"Tel Aviv", :birthdate=>"1997-06-27")
Client.create(:production_id=>1 ,:first_name=>"Eric", :last_name=>"Bell", :gender=>"male", :phone_number=>"0501811111", :city =>"Tel Aviv", :birthdate=>"1997-06-28")
Client.create(:production_id=>1 ,:first_name=>"Lester", :last_name=>"Erickson", :gender=>"male", :phone_number=>"0501911111", :city =>"Tel Aviv", :birthdate=>"1997-06-29")
Client.create(:production_id=>1 ,:first_name=>"Bennie", :last_name=>"Hernandez", :gender=>"male", :phone_number=>"0501011111", :city =>"Tel Aviv", :birthdate=>"1997-06-20")
Client.create(:production_id=>1 ,:first_name=>"Damon", :last_name=>"Warren", :gender=>"male", :phone_number=>"0501121111", :city =>"Ramat Gan", :birthdate=>"1997-07-20")
Client.create(:production_id=>1 ,:first_name=>"Blake", :last_name=>"Mcdaniel", :gender=>"male", :phone_number=>"0501131111", :city =>"Ramat Gan", :birthdate=>"1997-07-21")
Client.create(:production_id=>1 ,:first_name=>"Tomas", :last_name=>"Strickland", :gender=>"male", :phone_number=>"0501141111", :city =>"Ramat Gan", :birthdate=>"1997-07-22")
Client.create(:production_id=>1 ,:first_name=>"Howard", :last_name=>"Delgado", :gender=>"male", :phone_number=>"0501151111", :city =>"Ramat Gan", :birthdate=>"1997-07-23")
Client.create(:production_id=>1 ,:first_name=>"Dominic", :last_name=>"James", :gender=>"male", :phone_number=>"0501161111", :city =>"Ramat Gan", :birthdate=>"1997-07-24")
Client.create(:production_id=>1 ,:first_name=>"Seth", :last_name=>"Hughes", :gender=>"male", :phone_number=>"0501171111", :city =>"Ramat Gan", :birthdate=>"1997-07-25")
Client.create(:production_id=>1 ,:first_name=>"Jeremy", :last_name=>"Bowers", :gender=>"male", :phone_number=>"0501181111", :city =>"Ramat Gan", :birthdate=>"1997-07-26")
Client.create(:production_id=>1 ,:first_name=>"Ricky", :last_name=>"Doyle", :gender=>"male", :phone_number=>"0501191111", :city =>"Ramat Gan", :birthdate=>"1997-07-27")
Client.create(:production_id=>1 ,:first_name=>"Ismael", :last_name=>"Morris", :gender=>"male", :phone_number=>"0501101111", :city =>"Ramat Gan", :birthdate=>"1997-07-28")
Client.create(:production_id=>1 ,:first_name=>"Peter", :last_name=>"Lawson", :gender=>"male", :phone_number=>"0501111111", :city =>"Ramat Gan", :birthdate=>"1997-07-29")
Client.create(:production_id=>1 ,:first_name=>"Bradley", :last_name=>"Taylor", :gender=>"male", :phone_number=>"0501111111", :city =>"Raanana", :birthdate=>"1997-08-20")
Client.create(:production_id=>1 ,:first_name=>"Irvin", :last_name=>"Wong", :gender=>"male", :phone_number=>"0501112111", :city =>"Raanana", :birthdate=>"1997-08-21")
Client.create(:production_id=>1 ,:first_name=>"Clarence", :last_name=>"Blake", :gender=>"male", :phone_number=>"0501113111", :city =>"Raanana", :birthdate=>"1997-08-22")
Client.create(:production_id=>1 ,:first_name=>"Glenn", :last_name=>"May", :gender=>"male", :phone_number=>"0501114111", :city =>"Raanana", :birthdate=>"1997-08-23")
Client.create(:production_id=>1 ,:first_name=>"Claude", :last_name=>"Roberson", :gender=>"male", :phone_number=>"0501115111", :city =>"Raanana", :birthdate=>"1997-08-24")
Client.create(:production_id=>1 ,:first_name=>"Tyler", :last_name=>"King", :gender=>"male", :phone_number=>"0501116111", :city =>"Raanana", :birthdate=>"1997-08-25")
Client.create(:production_id=>1 ,:first_name=>"Neil", :last_name=>"Mckinney", :gender=>"male", :phone_number=>"0501117111", :city =>"Raanana", :birthdate=>"1997-08-26")
Client.create(:production_id=>1 ,:first_name=>"Jimmy", :last_name=>"Lyons", :gender=>"male", :phone_number=>"0501118111", :city =>"Raanana", :birthdate=>"1997-08-27")
Client.create(:production_id=>1 ,:first_name=>"Marion", :last_name=>"Lucas", :gender=>"male", :phone_number=>"0501119111", :city =>"Raanana", :birthdate=>"1997-08-28")
Client.create(:production_id=>1 ,:first_name=>"Lawrence", :last_name=>"Greene", :gender=>"male", :phone_number=>"0501110111", :city =>"Raanana", :birthdate=>"1997-08-29")
Client.create(:production_id=>1 ,:first_name=>"Ed", :last_name=>"Wolfe", :gender=>"male", :phone_number=>"0501111111", :city =>"Kfar Sava", :birthdate=>"1997-09-20")
Client.create(:production_id=>1 ,:first_name=>"Clifford", :last_name=>"Underwood", :gender=>"male", :phone_number=>"0501111211", :city =>"Kfar Sava", :birthdate=>"1997-09-21")
Client.create(:production_id=>1 ,:first_name=>"Darrell", :last_name=>"Page", :gender=>"male", :phone_number=>"0501111311", :city =>"Kfar Sava", :birthdate=>"1997-09-22")
Client.create(:production_id=>1 ,:first_name=>"Kenny", :last_name=>"Murray", :gender=>"male", :phone_number=>"0501111411", :city =>"Kfar Sava", :birthdate=>"1997-09-23")
Client.create(:production_id=>1 ,:first_name=>"Aaron", :last_name=>"Lynch", :gender=>"male", :phone_number=>"0501111511", :city =>"Kfar Sava", :birthdate=>"1997-09-24")
Client.create(:production_id=>1 ,:first_name=>"Rafael", :last_name=>"Guerrero", :gender=>"male", :phone_number=>"0501111611", :city =>"Kfar Sava", :birthdate=>"1997-09-25")
Client.create(:production_id=>1 ,:first_name=>"Willard", :last_name=>"Evans", :gender=>"male", :phone_number=>"0501111711", :city =>"Kfar Sava", :birthdate=>"1997-09-26")
Client.create(:production_id=>1 ,:first_name=>"Clint", :last_name=>"Wallace", :gender=>"male", :phone_number=>"0501111811", :city =>"Kfar Sava", :birthdate=>"1997-09-27")
Client.create(:production_id=>1 ,:first_name=>"Willie", :last_name=>"French", :gender=>"male", :phone_number=>"0501111911", :city =>"Kfar Sava", :birthdate=>"1997-09-28")
Client.create(:production_id=>1 ,:first_name=>"Lowell", :last_name=>"Gordon", :gender=>"male", :phone_number=>"0501111011", :city =>"Kfar Sava", :birthdate=>"1997-09-29")
Client.create(:production_id=>1 ,:first_name=>"Wallace", :last_name=>"Matthews", :gender=>"male", :phone_number=>"0501111111", :city =>"Jerusalem", :birthdate=>"1997-10-20")
Client.create(:production_id=>1 ,:first_name=>"Nir", :last_name=>"Webb", :gender=>"male", :phone_number=>"0501111121", :city =>"Jerusalem", :birthdate=>"1997-10-21")
Client.create(:production_id=>1 ,:first_name=>"Mack", :last_name=>"Dixon", :gender=>"male", :phone_number=>"0501111131", :city =>"Jerusalem", :birthdate=>"1997-10-22")
Client.create(:production_id=>1 ,:first_name=>"Jimmie", :last_name=>"Elliott", :gender=>"male", :phone_number=>"0501111141", :city =>"Jerusalem", :birthdate=>"1997-10-23")
Client.create(:production_id=>1 ,:first_name=>"Sylvester", :last_name=>"Nguyen", :gender=>"male", :phone_number=>"0501111151", :city =>"Jerusalem", :birthdate=>"1997-10-24")
Client.create(:production_id=>1 ,:first_name=>"Tony", :last_name=>"Payne", :gender=>"male", :phone_number=>"0501111161", :city =>"Jerusalem", :birthdate=>"1997-10-25")
Client.create(:production_id=>1 ,:first_name=>"Roderick", :last_name=>"Terry", :gender=>"male", :phone_number=>"0501111171", :city =>"Jerusalem", :birthdate=>"1997-10-26")
Client.create(:production_id=>1 ,:first_name=>"Micheal", :last_name=>"Ortiz", :gender=>"male", :phone_number=>"0501111181", :city =>"Jerusalem", :birthdate=>"1997-10-27")
Client.create(:production_id=>1 ,:first_name=>"Dallas", :last_name=>"Cunningham", :gender=>"male", :phone_number=>"0501111191", :city =>"Jerusalem", :birthdate=>"1997-10-28")
Client.create(:production_id=>1 ,:first_name=>"Willis", :last_name=>"Bridges", :gender=>"male", :phone_number=>"0501111101", :city =>"Jerusalem", :birthdate=>"1997-10-29")
Client.create(:production_id=>1 ,:first_name=>"Terrence", :last_name=>"Mcbride", :gender=>"male", :phone_number=>"0501111111", :city =>"Hedera", :birthdate=>"1997-11-20")
Client.create(:production_id=>1 ,:first_name=>"Bobby", :last_name=>"Fox", :gender=>"male", :phone_number=>"0501111112", :city =>"Hedera", :birthdate=>"1997-11-21")
Client.create(:production_id=>1 ,:first_name=>"Everett", :last_name=>"Joseph", :gender=>"male", :phone_number=>"0501111113", :city =>"Hedera", :birthdate=>"1997-11-22")
Client.create(:production_id=>1 ,:first_name=>"Freddie", :last_name=>"Lambert", :gender=>"male", :phone_number=>"0501111114", :city =>"Hedera", :birthdate=>"1997-11-23")
Client.create(:production_id=>1 ,:first_name=>"Gregory", :last_name=>"Powers", :gender=>"male", :phone_number=>"0501111115", :city =>"Hedera", :birthdate=>"1997-11-24")
Client.create(:production_id=>1 ,:first_name=>"Felix", :last_name=>"Dennis", :gender=>"male", :phone_number=>"0501111116", :city =>"Hedera", :birthdate=>"1997-11-25")
Client.create(:production_id=>1 ,:first_name=>"Carlos", :last_name=>"Burton", :gender=>"male", :phone_number=>"0501111117", :city =>"Hedera", :birthdate=>"1997-11-26")
Client.create(:production_id=>1 ,:first_name=>"Brett", :last_name=>"Crawford", :gender=>"male", :phone_number=>"0501111118", :city =>"Hedera", :birthdate=>"1997-11-27")
Client.create(:production_id=>1 ,:first_name=>"Angel", :last_name=>"Cruz", :gender=>"male", :phone_number=>"0501111119", :city =>"Hedera", :birthdate=>"1997-11-28")
Client.create(:production_id=>1 ,:first_name=>"Matthew", :last_name=>"Becker", :gender=>"male", :phone_number=>"0501111110", :city =>"Hedera", :birthdate=>"1997-11-29")
Client.create(:production_id=>1 ,:first_name=>"Angelo", :last_name=>"Duncan", :gender=>"male", :phone_number=>"0500011111", :city =>"Ashdod", :birthdate=>"1997-12-20")
Client.create(:production_id=>1 ,:first_name=>"Stanley", :last_name=>"Powell", :gender=>"male", :phone_number=>"0500021111", :city =>"Ashdod", :birthdate=>"1997-12-21")
Client.create(:production_id=>1 ,:first_name=>"Omar", :last_name=>"Owen", :gender=>"male", :phone_number=>"0500031111", :city =>"Ashdod", :birthdate=>"1997-12-22")
Client.create(:production_id=>1 ,:first_name=>"Cary", :last_name=>"Fields", :gender=>"male", :phone_number=>"0500041111", :city =>"Ashdod", :birthdate=>"1997-12-23")
Client.create(:production_id=>1 ,:first_name=>"Orlando", :last_name=>"Jones", :gender=>"male", :phone_number=>"0500051111", :city =>"Ashdod", :birthdate=>"1997-12-24")
Client.create(:production_id=>1 ,:first_name=>"Cory", :last_name=>"Simon", :gender=>"male", :phone_number=>"0500061111", :city =>"Ashdod", :birthdate=>"1997-12-25")
Client.create(:production_id=>1 ,:first_name=>"Joe", :last_name=>"Gonzales", :gender=>"male", :phone_number=>"0500071111", :city =>"Ashdod", :birthdate=>"1997-12-26")
Client.create(:production_id=>1 ,:first_name=>"Joshua", :last_name=>"Warner", :gender=>"male", :phone_number=>"0500081111", :city =>"Ashdod", :birthdate=>"1997-12-27")
Client.create(:production_id=>1 ,:first_name=>"Derrick", :last_name=>"Malone", :gender=>"male", :phone_number=>"0500091111", :city =>"Ashdod", :birthdate=>"1997-12-28")
Client.create(:production_id=>1 ,:first_name=>"Ruben", :last_name=>"Harvey", :gender=>"male", :phone_number=>"0500001111", :city =>"Ashdod", :birthdate=>"1997-12-29")
Client.create(:production_id=>1 ,:first_name=>"Emmett", :last_name=>"Mccoy", :gender=>"male", :phone_number=>"0500011111", :city =>"Holon", :birthdate=>"1997-01-20")
Client.create(:production_id=>1 ,:first_name=>"Ramiro", :last_name=>"Washington", :gender=>"male", :phone_number=>"0500012111", :city =>"Holon", :birthdate=>"1997-01-21")
Client.create(:production_id=>1 ,:first_name=>"Elmer", :last_name=>"Bryant", :gender=>"male", :phone_number=>"0500013111", :city =>"Holon", :birthdate=>"1997-01-22")
Client.create(:production_id=>1 ,:first_name=>"Hugh", :last_name=>"Reid", :gender=>"male", :phone_number=>"0500014111", :city =>"Holon", :birthdate=>"1997-01-23")
Client.create(:production_id=>1 ,:first_name=>"Steve", :last_name=>"Greer", :gender=>"male", :phone_number=>"0500015111", :city =>"Holon", :birthdate=>"1997-01-24")
Client.create(:production_id=>1 ,:first_name=>"Rickey", :last_name=>"Huff", :gender=>"male", :phone_number=>"0500016111", :city =>"Holon", :birthdate=>"1997-01-25")
Client.create(:production_id=>1 ,:first_name=>"Mathew", :last_name=>"Lopez", :gender=>"male", :phone_number=>"0500017111", :city =>"Holon", :birthdate=>"1997-01-26")
Client.create(:production_id=>1 ,:first_name=>"Donald", :last_name=>"Waters", :gender=>"male", :phone_number=>"0500018111", :city =>"Holon", :birthdate=>"1997-01-27")
Client.create(:production_id=>1 ,:first_name=>"Van", :last_name=>"Miles", :gender=>"male", :phone_number=>"0500019111", :city =>"Holon", :birthdate=>"1997-01-28")
Client.create(:production_id=>1 ,:first_name=>"Gilbert", :last_name=>"Boone", :gender=>"male", :phone_number=>"0500010111", :city =>"Holon", :birthdate=>"1997-01-29")
Client.create(:production_id=>1 ,:first_name=>"Alexander", :last_name=>"Walters", :gender=>"male", :phone_number=>"0500011111", :city =>"Herzliya", :birthdate=>"1997-02-20")
Client.create(:production_id=>1 ,:first_name=>"Josh", :last_name=>"Cole", :gender=>"male", :phone_number=>"0500011211", :city =>"Herzliya", :birthdate=>"1997-02-21")
Client.create(:production_id=>1 ,:first_name=>"Sean", :last_name=>"Peters", :gender=>"male", :phone_number=>"0500011311", :city =>"Herzliya", :birthdate=>"1997-02-22")
Client.create(:production_id=>1 ,:first_name=>"Ian", :last_name=>"Phillips", :gender=>"male", :phone_number=>"0500011411", :city =>"Herzliya", :birthdate=>"1997-02-23")
Client.create(:production_id=>1 ,:first_name=>"Lyle", :last_name=>"Spencer", :gender=>"male", :phone_number=>"0500011511", :city =>"Herzliya", :birthdate=>"1997-02-24")
Client.create(:production_id=>1 ,:first_name=>"Courtney", :last_name=>"Perez", :gender=>"male", :phone_number=>"0500011611", :city =>"Herzliya", :birthdate=>"1997-02-25")
Client.create(:production_id=>1 ,:first_name=>"Abel", :last_name=>"Ruiz", :gender=>"male", :phone_number=>"0500011711", :city =>"Herzliya", :birthdate=>"1997-02-26")
Client.create(:production_id=>1 ,:first_name=>"Gustavo", :last_name=>"Adams", :gender=>"male", :phone_number=>"0500011811", :city =>"Herzliya", :birthdate=>"1997-02-27")
Client.create(:production_id=>1 ,:first_name=>"Alonzo", :last_name=>"Bowman", :gender=>"male", :phone_number=>"0500011911", :city =>"Herzliya", :birthdate=>"1997-02-28")
Client.create(:production_id=>1 ,:first_name=>"David", :last_name=>"Steele", :gender=>"male", :phone_number=>"0500011011", :city =>"Herzliya", :birthdate=>"1997-02-29")
Client.create(:production_id=>1 ,:first_name=>"Sara", :last_name=>"Hunt", :gender=>"female", :phone_number=>"0521111111", :city =>"Tel Mond", :birthdate=>"1997-05-21")
Client.create(:production_id=>1 ,:first_name=>"Sadie", :last_name=>"Willis", :gender=>"female", :phone_number=>"0522111111", :city =>"Tel Mond", :birthdate=>"1997-05-22")
Client.create(:production_id=>1 ,:first_name=>"Marsha", :last_name=>"Barnes", :gender=>"female", :phone_number=>"0523111111", :city =>"Tel Mond", :birthdate=>"1997-05-23")
Client.create(:production_id=>1 ,:first_name=>"Diana", :last_name=>"Hill", :gender=>"female", :phone_number=>"0524111111", :city =>"Tel Mond", :birthdate=>"1997-05-24")
Client.create(:production_id=>1 ,:first_name=>"Kerry", :last_name=>"Mann", :gender=>"female", :phone_number=>"0525111111", :city =>"Tel Mond", :birthdate=>"1997-05-25")
Client.create(:production_id=>1 ,:first_name=>"Audrey", :last_name=>"Mccarthy", :gender=>"female", :phone_number=>"0526111111", :city =>"Tel Mond", :birthdate=>"1997-05-26")
Client.create(:production_id=>1 ,:first_name=>"Mercedes", :last_name=>"Valdez", :gender=>"female", :phone_number=>"0527111111", :city =>"Tel Mond", :birthdate=>"1997-05-27")
Client.create(:production_id=>1 ,:first_name=>"Donna", :last_name=>"Neal", :gender=>"female", :phone_number=>"0528111111", :city =>"Tel Mond", :birthdate=>"1997-05-28")
Client.create(:production_id=>1 ,:first_name=>"Joyce", :last_name=>"Parks", :gender=>"female", :phone_number=>"0529111111", :city =>"Tel Mond", :birthdate=>"1997-05-29")
Client.create(:production_id=>1 ,:first_name=>"Laura", :last_name=>"Gilbert", :gender=>"female", :phone_number=>"0520111111", :city =>"Tel Mond", :birthdate=>"1997-05-80")
Client.create(:production_id=>1 ,:first_name=>"Heather", :last_name=>"Wilkins", :gender=>"female", :phone_number=>"0521111111", :city =>"Tel Aviv", :birthdate=>"1997-06-21")
Client.create(:production_id=>1 ,:first_name=>"Ann", :last_name=>"Frazier", :gender=>"female", :phone_number=>"0521211111", :city =>"Tel Aviv", :birthdate=>"1997-06-22")
Client.create(:production_id=>1 ,:first_name=>"Theresa", :last_name=>"Daniels", :gender=>"female", :phone_number=>"0521311111", :city =>"Tel Aviv", :birthdate=>"1997-06-23")
Client.create(:production_id=>1 ,:first_name=>"Margaret", :last_name=>"Cummings", :gender=>"female", :phone_number=>"0521411111", :city =>"Tel Aviv", :birthdate=>"1997-06-24")
Client.create(:production_id=>1 ,:first_name=>"Susan", :last_name=>"Austin", :gender=>"female", :phone_number=>"0521511111", :city =>"Tel Aviv", :birthdate=>"1997-06-25")
Client.create(:production_id=>1 ,:first_name=>"Stephanie", :last_name=>"Sparks", :gender=>"female", :phone_number=>"0521611111", :city =>"Tel Aviv", :birthdate=>"1997-06-26")
Client.create(:production_id=>1 ,:first_name=>"Karen", :last_name=>"Grant", :gender=>"female", :phone_number=>"0521711111", :city =>"Tel Aviv", :birthdate=>"1997-06-27")
Client.create(:production_id=>1 ,:first_name=>"Sarah", :last_name=>"Bell", :gender=>"female", :phone_number=>"0521811111", :city =>"Tel Aviv", :birthdate=>"1997-06-28")
Client.create(:production_id=>1 ,:first_name=>"Rachel", :last_name=>"Erickson", :gender=>"female", :phone_number=>"0521911111", :city =>"Tel Aviv", :birthdate=>"1997-06-29")
Client.create(:production_id=>1 ,:first_name=>"Kathy", :last_name=>"Hernandez", :gender=>"female", :phone_number=>"0521011111", :city =>"Tel Aviv", :birthdate=>"1997-06-20")
Client.create(:production_id=>1 ,:first_name=>"Deborah", :last_name=>"Warren", :gender=>"female", :phone_number=>"0521121111", :city =>"Ramat Gan", :birthdate=>"1997-07-20")
Client.create(:production_id=>1 ,:first_name=>"Amanda", :last_name=>"Mcdaniel", :gender=>"female", :phone_number=>"0521131111", :city =>"Ramat Gan", :birthdate=>"1997-07-21")
Client.create(:production_id=>1 ,:first_name=>"Kathleen", :last_name=>"Strickland", :gender=>"female", :phone_number=>"0521141111", :city =>"Ramat Gan", :birthdate=>"1997-07-22")
Client.create(:production_id=>1 ,:first_name=>"Annie", :last_name=>"Delgado", :gender=>"female", :phone_number=>"0521151111", :city =>"Ramat Gan", :birthdate=>"1997-07-23")
Client.create(:production_id=>1 ,:first_name=>"Ashley", :last_name=>"James", :gender=>"female", :phone_number=>"0521161111", :city =>"Ramat Gan", :birthdate=>"1997-07-24")
Client.create(:production_id=>1 ,:first_name=>"Dorothy", :last_name=>"Hughes", :gender=>"female", :phone_number=>"0521171111", :city =>"Ramat Gan", :birthdate=>"1997-07-25")
Client.create(:production_id=>1 ,:first_name=>"Gloria", :last_name=>"Bowers", :gender=>"female", :phone_number=>"0521181111", :city =>"Ramat Gan", :birthdate=>"1997-07-26")
Client.create(:production_id=>1 ,:first_name=>"Jane", :last_name=>"Doyle", :gender=>"female", :phone_number=>"0521191111", :city =>"Ramat Gan", :birthdate=>"1997-07-27")
Client.create(:production_id=>1 ,:first_name=>"Brenda", :last_name=>"Morris", :gender=>"female", :phone_number=>"0521101111", :city =>"Ramat Gan", :birthdate=>"1997-07-28")
Client.create(:production_id=>1 ,:first_name=>"Janet", :last_name=>"Lawson", :gender=>"female", :phone_number=>"0521111111", :city =>"Ramat Gan", :birthdate=>"1997-07-29")
Client.create(:production_id=>1 ,:first_name=>"Emily", :last_name=>"Taylor", :gender=>"female", :phone_number=>"0521111111", :city =>"Raanana", :birthdate=>"1997-08-20")
Client.create(:production_id=>1 ,:first_name=>"Janice", :last_name=>"Wong", :gender=>"female", :phone_number=>"0521112111", :city =>"Raanana", :birthdate=>"1997-08-21")
Client.create(:production_id=>1 ,:first_name=>"Sharon", :last_name=>"Blake", :gender=>"female", :phone_number=>"0521113111", :city =>"Raanana", :birthdate=>"1997-08-22")
Client.create(:production_id=>1 ,:first_name=>"Marie", :last_name=>"May", :gender=>"female", :phone_number=>"0521114111", :city =>"Raanana", :birthdate=>"1997-08-23")
Client.create(:production_id=>1 ,:first_name=>"Irene", :last_name=>"Roberson", :gender=>"female", :phone_number=>"0521115111", :city =>"Raanana", :birthdate=>"1997-08-24")
Client.create(:production_id=>1 ,:first_name=>"Mary", :last_name=>"King", :gender=>"female", :phone_number=>"0521116111", :city =>"Raanana", :birthdate=>"1997-08-25")
Client.create(:production_id=>1 ,:first_name=>"Betty", :last_name=>"Mckinney", :gender=>"female", :phone_number=>"0521117111", :city =>"Raanana", :birthdate=>"1997-08-26")
Client.create(:production_id=>1 ,:first_name=>"Phyllis", :last_name=>"Lyons", :gender=>"female", :phone_number=>"0521118111", :city =>"Raanana", :birthdate=>"1997-08-27")
Client.create(:production_id=>1 ,:first_name=>"Helen", :last_name=>"Lucas", :gender=>"female", :phone_number=>"0521119111", :city =>"Raanana", :birthdate=>"1997-08-28")
Client.create(:production_id=>1 ,:first_name=>"Martha", :last_name=>"Greene", :gender=>"female", :phone_number=>"0521110111", :city =>"Raanana", :birthdate=>"1997-08-29")
Client.create(:production_id=>1 ,:first_name=>"Cheryl", :last_name=>"Wolfe", :gender=>"female", :phone_number=>"0521111111", :city =>"Kfar Sava", :birthdate=>"1997-09-20")
Client.create(:production_id=>1 ,:first_name=>"Patricia", :last_name=>"Underwood", :gender=>"female", :phone_number=>"0521111211", :city =>"Kfar Sava", :birthdate=>"1997-09-21")
Client.create(:production_id=>1 ,:first_name=>"Michelle", :last_name=>"Page", :gender=>"female", :phone_number=>"0521111311", :city =>"Kfar Sava", :birthdate=>"1997-09-22")
Client.create(:production_id=>1 ,:first_name=>"Lori", :last_name=>"Murray", :gender=>"female", :phone_number=>"0521111411", :city =>"Kfar Sava", :birthdate=>"1997-09-23")
Client.create(:production_id=>1 ,:first_name=>"Pamela", :last_name=>"Lynch", :gender=>"female", :phone_number=>"0521111511", :city =>"Kfar Sava", :birthdate=>"1997-09-24")
Client.create(:production_id=>1 ,:first_name=>"Andrea", :last_name=>"Guerrero", :gender=>"female", :phone_number=>"0521111611", :city =>"Kfar Sava", :birthdate=>"1997-09-25")
Client.create(:production_id=>1 ,:first_name=>"Christine", :last_name=>"Evans", :gender=>"female", :phone_number=>"0521111711", :city =>"Kfar Sava", :birthdate=>"1997-09-26")
Client.create(:production_id=>1 ,:first_name=>"Katherine", :last_name=>"Wallace", :gender=>"female", :phone_number=>"0521111811", :city =>"Kfar Sava", :birthdate=>"1997-09-27")
Client.create(:production_id=>1 ,:first_name=>"Catherine", :last_name=>"French", :gender=>"female", :phone_number=>"0521111911", :city =>"Kfar Sava", :birthdate=>"1997-09-28")
Client.create(:production_id=>1 ,:first_name=>"Kelly", :last_name=>"Gordon", :gender=>"female", :phone_number=>"0521111011", :city =>"Kfar Sava", :birthdate=>"1997-09-29")
Client.create(:production_id=>1 ,:first_name=>"Nicole", :last_name=>"Matthews", :gender=>"female", :phone_number=>"0521111111", :city =>"Jerusalem", :birthdate=>"1997-10-20")
Client.create(:production_id=>1 ,:first_name=>"Anne", :last_name=>"Webb", :gender=>"female", :phone_number=>"0521111121", :city =>"Jerusalem", :birthdate=>"1997-10-21")
Client.create(:production_id=>1 ,:first_name=>"Louise", :last_name=>"Dixon", :gender=>"female", :phone_number=>"0521111131", :city =>"Jerusalem", :birthdate=>"1997-10-22")
Client.create(:production_id=>1 ,:first_name=>"Frances", :last_name=>"Elliott", :gender=>"female", :phone_number=>"0521111141", :city =>"Jerusalem", :birthdate=>"1997-10-23")
Client.create(:production_id=>1 ,:first_name=>"Elizabeth", :last_name=>"Nguyen", :gender=>"female", :phone_number=>"0521111151", :city =>"Jerusalem", :birthdate=>"1997-10-24")
Client.create(:production_id=>1 ,:first_name=>"Maria", :last_name=>"Payne", :gender=>"female", :phone_number=>"0521111161", :city =>"Jerusalem", :birthdate=>"1997-10-25")
Client.create(:production_id=>1 ,:first_name=>"Ruby", :last_name=>"Terry", :gender=>"female", :phone_number=>"0521111171", :city =>"Jerusalem", :birthdate=>"1997-10-26")
Client.create(:production_id=>1 ,:first_name=>"Joan", :last_name=>"Ortiz", :gender=>"female", :phone_number=>"0521111181", :city =>"Jerusalem", :birthdate=>"1997-10-27")
Client.create(:production_id=>1 ,:first_name=>"Kimberly", :last_name=>"Cunningham", :gender=>"female", :phone_number=>"0521111191", :city =>"Jerusalem", :birthdate=>"1997-10-28")
Client.create(:production_id=>1 ,:first_name=>"Jessica", :last_name=>"Bridges", :gender=>"female", :phone_number=>"0521111101", :city =>"Jerusalem", :birthdate=>"1997-10-29")
Client.create(:production_id=>1 ,:first_name=>"Denise", :last_name=>"Mcbride", :gender=>"female", :phone_number=>"0521111111", :city =>"Hedera", :birthdate=>"1997-11-20")
Client.create(:production_id=>1 ,:first_name=>"Cynthia", :last_name=>"Fox", :gender=>"female", :phone_number=>"0521111112", :city =>"Hedera", :birthdate=>"1997-11-21")
Client.create(:production_id=>1 ,:first_name=>"Evelyn", :last_name=>"Joseph", :gender=>"female", :phone_number=>"0521111113", :city =>"Hedera", :birthdate=>"1997-11-22")
Client.create(:production_id=>1 ,:first_name=>"Teresa", :last_name=>"Lambert", :gender=>"female", :phone_number=>"0521111114", :city =>"Hedera", :birthdate=>"1997-11-23")
Client.create(:production_id=>1 ,:first_name=>"Doris", :last_name=>"Powers", :gender=>"female", :phone_number=>"0521111115", :city =>"Hedera", :birthdate=>"1997-11-24")
Client.create(:production_id=>1 ,:first_name=>"Paula", :last_name=>"Dennis", :gender=>"female", :phone_number=>"0521111116", :city =>"Hedera", :birthdate=>"1997-11-25")
Client.create(:production_id=>1 ,:first_name=>"Julie", :last_name=>"Burton", :gender=>"female", :phone_number=>"0521111117", :city =>"Hedera", :birthdate=>"1997-11-26")
Client.create(:production_id=>1 ,:first_name=>"Christina", :last_name=>"Crawford", :gender=>"female", :phone_number=>"0521111118", :city =>"Hedera", :birthdate=>"1997-11-27")
Client.create(:production_id=>1 ,:first_name=>"Rose", :last_name=>"Cruz", :gender=>"female", :phone_number=>"0521111119", :city =>"Hedera", :birthdate=>"1997-11-28")
Client.create(:production_id=>1 ,:first_name=>"Debra", :last_name=>"Becker", :gender=>"female", :phone_number=>"0521111110", :city =>"Hedera", :birthdate=>"1997-11-29")
Client.create(:production_id=>1 ,:first_name=>"Judith", :last_name=>"Duncan", :gender=>"female", :phone_number=>"0520011111", :city =>"Ashdod", :birthdate=>"1997-12-20")
Client.create(:production_id=>1 ,:first_name=>"Alice", :last_name=>"Powell", :gender=>"female", :phone_number=>"0520021111", :city =>"Ashdod", :birthdate=>"1997-12-21")
Client.create(:production_id=>1 ,:first_name=>"Ruth", :last_name=>"Owen", :gender=>"female", :phone_number=>"0520031111", :city =>"Ashdod", :birthdate=>"1997-12-22")
Client.create(:production_id=>1 ,:first_name=>"Angela", :last_name=>"Fields", :gender=>"female", :phone_number=>"0520041111", :city =>"Ashdod", :birthdate=>"1997-12-23")
Client.create(:production_id=>1 ,:first_name=>"Norma", :last_name=>"Jones", :gender=>"female", :phone_number=>"0520051111", :city =>"Ashdod", :birthdate=>"1997-12-24")
Client.create(:production_id=>1 ,:first_name=>"Kathryn", :last_name=>"Simon", :gender=>"female", :phone_number=>"0520061111", :city =>"Ashdod", :birthdate=>"1997-12-25")
Client.create(:production_id=>1 ,:first_name=>"Nancy", :last_name=>"Gonzales", :gender=>"female", :phone_number=>"0520071111", :city =>"Ashdod", :birthdate=>"1997-12-26")
Client.create(:production_id=>1 ,:first_name=>"Amy", :last_name=>"Warner", :gender=>"female", :phone_number=>"0520081111", :city =>"Ashdod", :birthdate=>"1997-12-27")
Client.create(:production_id=>1 ,:first_name=>"Carol", :last_name=>"Malone", :gender=>"female", :phone_number=>"0520091111", :city =>"Ashdod", :birthdate=>"1997-12-28")
Client.create(:production_id=>1 ,:first_name=>"Tammy", :last_name=>"Harvey", :gender=>"female", :phone_number=>"0520001111", :city =>"Ashdod", :birthdate=>"1997-12-29")
Client.create(:production_id=>1 ,:first_name=>"Emmett", :last_name=>"Mccoy", :gender=>"female", :phone_number=>"0520011111", :city =>"Holon", :birthdate=>"1997-01-20")
Client.create(:production_id=>1 ,:first_name=>"Rebecca", :last_name=>"Washington", :gender=>"female", :phone_number=>"0520012111", :city =>"Holon", :birthdate=>"1997-01-21")
Client.create(:production_id=>1 ,:first_name=>"Elmer", :last_name=>"Bryant", :gender=>"female", :phone_number=>"0520013111", :city =>"Holon", :birthdate=>"1997-01-22")
Client.create(:production_id=>1 ,:first_name=>"Lillian", :last_name=>"Reid", :gender=>"female", :phone_number=>"0520014111", :city =>"Holon", :birthdate=>"1997-01-23")
Client.create(:production_id=>1 ,:first_name=>"Jennifer", :last_name=>"Greer", :gender=>"female", :phone_number=>"0520015111", :city =>"Holon", :birthdate=>"1997-01-24")
Client.create(:production_id=>1 ,:first_name=>"Rickey", :last_name=>"Huff", :gender=>"female", :phone_number=>"0520016111", :city =>"Holon", :birthdate=>"1997-01-25")
Client.create(:production_id=>1 ,:first_name=>"Marilyn", :last_name=>"Lopez", :gender=>"female", :phone_number=>"0520017111", :city =>"Holon", :birthdate=>"1997-01-26")
Client.create(:production_id=>1 ,:first_name=>"Diana", :last_name=>"Waters", :gender=>"female", :phone_number=>"0520018111", :city =>"Holon", :birthdate=>"1997-01-27")
Client.create(:production_id=>1 ,:first_name=>"Sandra", :last_name=>"Miles", :gender=>"female", :phone_number=>"0520019111", :city =>"Holon", :birthdate=>"1997-01-28")
Client.create(:production_id=>1 ,:first_name=>"Julia", :last_name=>"Boone", :gender=>"female", :phone_number=>"0520010111", :city =>"Holon", :birthdate=>"1997-01-29")
Client.create(:production_id=>1 ,:first_name=>"Jacqueline", :last_name=>"Walters", :gender=>"female", :phone_number=>"0520011111", :city =>"Herzliya", :birthdate=>"1997-02-20")
Client.create(:production_id=>1 ,:first_name=>"Melissa", :last_name=>"Cole", :gender=>"female", :phone_number=>"0520011211", :city =>"Herzliya", :birthdate=>"1997-02-21")
Client.create(:production_id=>1 ,:first_name=>"Wanda", :last_name=>"Peters", :gender=>"female", :phone_number=>"0520011311", :city =>"Herzliya", :birthdate=>"1997-02-22")
Client.create(:production_id=>1 ,:first_name=>"Lisa", :last_name=>"Phillips", :gender=>"female", :phone_number=>"0520011411", :city =>"Herzliya", :birthdate=>"1997-02-23")
Client.create(:production_id=>1 ,:first_name=>"Lyle", :last_name=>"Spencer", :gender=>"female", :phone_number=>"0520011511", :city =>"Herzliya", :birthdate=>"1997-02-24")
Client.create(:production_id=>1 ,:first_name=>"Bonnie", :last_name=>"Perez", :gender=>"female", :phone_number=>"0520011611", :city =>"Herzliya", :birthdate=>"1997-02-25")
Client.create(:production_id=>1 ,:first_name=>"Barbara", :last_name=>"Ruiz", :gender=>"female", :phone_number=>"0520011711", :city =>"Herzliya", :birthdate=>"1997-02-26")
Client.create(:production_id=>1 ,:first_name=>"Virginia", :last_name=>"Adams", :gender=>"female", :phone_number=>"0520011811", :city =>"Herzliya", :birthdate=>"1997-02-27")
Client.create(:production_id=>1 ,:first_name=>"Mildred", :last_name=>"Bowman", :gender=>"female", :phone_number=>"0520011911", :city =>"Herzliya", :birthdate=>"1997-02-28")
Client.create(:production_id=>1 ,:first_name=>"Carolyn", :last_name=>"Steele", :gender=>"female", :phone_number=>"0520011011", :city =>"Herzliya", :birthdate=>"1997-02-29")

# events
Event.create(:production_id=>1, :user_id=>1, :name=>"Sound Of Sunset", :when=>"2014-09-01 22:30:00")
Event.create(:production_id=>1, :user_id=>1, :name=>"Color Festival", :when=>"2014-09-07 22:30:00")
Event.create(:production_id=>1, :user_id=>2, :name=>"Friends Party", :when=>"2015-09-14 22:30:00")

# prices for first event
EventPrice.create(:event_id=>1, :price=>"0")
EventPrice.create(:event_id=>1, :price=>"5")
EventPrice.create(:event_id=>1, :price=>"10")

# prices for second event
EventPrice.create(:event_id=>2, :price=>"0")
EventPrice.create(:event_id=>2, :price=>"8")
EventPrice.create(:event_id=>2, :price=>"10")

# prices for third event
EventPrice.create(:event_id=>3, :price=>"5")
EventPrice.create(:event_id=>3, :price=>"10")
EventPrice.create(:event_id=>3, :price=>"15")

# tickets for first event by first promoter
Ticket.create(:event_id=>1, :client_id=>1, :promoter_id=>3, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>2, :promoter_id=>3, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>3, :promoter_id=>3, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>1, :client_id=>12, :promoter_id=>3, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>23, :promoter_id=>3, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>34, :promoter_id=>3, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>1, :client_id=>5, :promoter_id=>3, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>27, :promoter_id=>3, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>90, :promoter_id=>3, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>1, :client_id=>143, :promoter_id=>3, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>124, :promoter_id=>3, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>107, :promoter_id=>3, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>54, :promoter_id=>3, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>67, :promoter_id=>3, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>89, :promoter_id=>3, :event_price_id=>3, :reason=>"Good boy!")

# tickets for first event by second promoter
Ticket.create(:event_id=>1, :client_id=>1, :promoter_id=>4, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>2, :promoter_id=>4, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>3, :promoter_id=>4, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>45, :promoter_id=>4, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>16, :promoter_id=>4, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>17, :promoter_id=>4, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>108, :promoter_id=>4, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>143, :promoter_id=>4, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>156, :promoter_id=>4, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>1, :client_id=>178, :promoter_id=>4, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>109, :promoter_id=>4, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>134, :promoter_id=>4, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>1, :client_id=>67, :promoter_id=>4, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>87, :promoter_id=>4, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>94, :promoter_id=>4, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)

# tickets for first event by third promoter
Ticket.create(:event_id=>1, :client_id=>1, :promoter_id=>5, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>2, :promoter_id=>5, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>3, :promoter_id=>5, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>54, :promoter_id=>5, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>132, :promoter_id=>5, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>46, :promoter_id=>5, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>97, :promoter_id=>5, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>100, :promoter_id=>5, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>10, :promoter_id=>5, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>14, :promoter_id=>5, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>27, :promoter_id=>5, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>48, :promoter_id=>5, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>1, :client_id=>33, :promoter_id=>5, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>32, :promoter_id=>5, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>37, :promoter_id=>5, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)

# tickets for first event by 4th promoter
Ticket.create(:event_id=>1, :client_id=>1, :promoter_id=>6, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>2, :promoter_id=>6, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>3, :promoter_id=>6, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>146, :promoter_id=>6, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>191, :promoter_id=>6, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>187, :promoter_id=>6, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>1, :client_id=>15, :promoter_id=>6, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>121, :promoter_id=>6, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>120, :promoter_id=>6, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>1, :client_id=>17, :promoter_id=>6, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>140, :promoter_id=>6, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>170, :promoter_id=>6, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>1, :client_id=>177, :promoter_id=>6, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>160, :promoter_id=>6, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>190, :promoter_id=>6, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)

# tickets for first event by 5th promoter
Ticket.create(:event_id=>1, :client_id=>1, :promoter_id=>7, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>2, :promoter_id=>7, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>3, :promoter_id=>7, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>105, :promoter_id=>7, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>14, :promoter_id=>7, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>107, :promoter_id=>7, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>102, :promoter_id=>7, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>126, :promoter_id=>7, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>185, :promoter_id=>7, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>146, :promoter_id=>7, :event_price_id=>1, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>141, :promoter_id=>7, :event_price_id=>2, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>139, :promoter_id=>7, :event_price_id=>3, :reason=>"Good boy!")
Ticket.create(:event_id=>1, :client_id=>109, :promoter_id=>7, :event_price_id=>1, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>1, :client_id=>60, :promoter_id=>7, :event_price_id=>2, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>1, :client_id=>177, :promoter_id=>7, :event_price_id=>3, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)

# tickets for second event by first promoter
Ticket.create(:event_id=>2, :client_id=>1, :promoter_id=>3, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>2, :promoter_id=>3, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>3, :promoter_id=>3, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>2, :client_id=>12, :promoter_id=>3, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>43, :promoter_id=>3, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>64, :promoter_id=>3, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>2, :client_id=>50, :promoter_id=>3, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>47, :promoter_id=>3, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>6, :promoter_id=>3, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>2, :client_id=>13, :promoter_id=>3, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>14, :promoter_id=>3, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>17, :promoter_id=>3, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>154, :promoter_id=>3, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>167, :promoter_id=>3, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>189, :promoter_id=>3, :event_price_id=>6, :reason=>"Good boy!")

# tickets for second event by second promoter
Ticket.create(:event_id=>2, :client_id=>1, :promoter_id=>4, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>2, :promoter_id=>4, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>3, :promoter_id=>4, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>145, :promoter_id=>4, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>116, :promoter_id=>4, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>117, :promoter_id=>4, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>18, :promoter_id=>4, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>13, :promoter_id=>4, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>16, :promoter_id=>4, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>2, :client_id=>78, :promoter_id=>4, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>10, :promoter_id=>4, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>14, :promoter_id=>4, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>2, :client_id=>167, :promoter_id=>4, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>187, :promoter_id=>4, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>194, :promoter_id=>4, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)

# tickets for second event by third promoter
Ticket.create(:event_id=>2, :client_id=>1, :promoter_id=>5, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>2, :promoter_id=>5, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>3, :promoter_id=>5, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>154, :promoter_id=>5, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>32, :promoter_id=>5, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>6, :promoter_id=>5, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>197, :promoter_id=>5, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>120, :promoter_id=>5, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>101, :promoter_id=>5, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>141, :promoter_id=>5, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>127, :promoter_id=>5, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>148, :promoter_id=>5, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>2, :client_id=>133, :promoter_id=>5, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>132, :promoter_id=>5, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>137, :promoter_id=>5, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)

# tickets for second event by 4th promoter
Ticket.create(:event_id=>2, :client_id=>1, :promoter_id=>6, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>2, :promoter_id=>6, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>3, :promoter_id=>6, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>16, :promoter_id=>6, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>91, :promoter_id=>6, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>87, :promoter_id=>6, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>2, :client_id=>13, :promoter_id=>6, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>11, :promoter_id=>6, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>20, :promoter_id=>6, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>2, :client_id=>12, :promoter_id=>6, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>136, :promoter_id=>6, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>171, :promoter_id=>6, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)
Ticket.create(:event_id=>2, :client_id=>12, :promoter_id=>6, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>180, :promoter_id=>6, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>140, :promoter_id=>6, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)

# tickets for second event by 5th promoter
Ticket.create(:event_id=>2, :client_id=>1, :promoter_id=>7, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>2, :promoter_id=>7, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>3, :promoter_id=>7, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>15, :promoter_id=>7, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>124, :promoter_id=>7, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>107, :promoter_id=>7, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>102, :promoter_id=>7, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>126, :promoter_id=>7, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>135, :promoter_id=>7, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>146, :promoter_id=>7, :event_price_id=>4, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>141, :promoter_id=>7, :event_price_id=>5, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>149, :promoter_id=>7, :event_price_id=>6, :reason=>"Good boy!")
Ticket.create(:event_id=>2, :client_id=>19, :promoter_id=>7, :event_price_id=>4, :reason=>"Good boy!", :arrived=>true, :cashier_id=>8)
Ticket.create(:event_id=>2, :client_id=>160, :promoter_id=>7, :event_price_id=>5, :reason=>"Good boy!", :arrived=>true, :cashier_id=>9)
Ticket.create(:event_id=>2, :client_id=>17, :promoter_id=>7, :event_price_id=>6, :reason=>"Good boy!", :arrived=>true, :cashier_id=>10)

# tickets for third event by first promoter
Ticket.create(:event_id=>3, :client_id=>1, :promoter_id=>3, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>2, :promoter_id=>3, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>3, :promoter_id=>3, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>12, :promoter_id=>3, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>43, :promoter_id=>3, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>64, :promoter_id=>3, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>20, :promoter_id=>3, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>47, :promoter_id=>3, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>64, :promoter_id=>3, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>15, :promoter_id=>3, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>13, :promoter_id=>3, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>171, :promoter_id=>3, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>14, :promoter_id=>3, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>17, :promoter_id=>3, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>149, :promoter_id=>3, :event_price_id=>9, :reason=>"Good boy!")

# tickets for third event by second promoter
Ticket.create(:event_id=>3, :client_id=>1, :promoter_id=>4, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>2, :promoter_id=>4, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>3, :promoter_id=>4, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>15, :promoter_id=>4, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>16, :promoter_id=>4, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>17, :promoter_id=>4, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>131, :promoter_id=>4, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>135, :promoter_id=>4, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>167, :promoter_id=>4, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>72, :promoter_id=>4, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>120, :promoter_id=>4, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>143, :promoter_id=>4, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>16, :promoter_id=>4, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>18, :promoter_id=>4, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>194, :promoter_id=>4, :event_price_id=>9, :reason=>"Good boy!")

# tickets for third event by third promoter
Ticket.create(:event_id=>3, :client_id=>1, :promoter_id=>5, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>2, :promoter_id=>5, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>3, :promoter_id=>5, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>154, :promoter_id=>5, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>32, :promoter_id=>5, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>6, :promoter_id=>5, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>127, :promoter_id=>5, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>12, :promoter_id=>5, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>101, :promoter_id=>5, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>141, :promoter_id=>5, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>137, :promoter_id=>5, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>148, :promoter_id=>5, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>143, :promoter_id=>5, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>152, :promoter_id=>5, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>187, :promoter_id=>5, :event_price_id=>9, :reason=>"Good boy!")

# tickets for third event by 4th promoter
Ticket.create(:event_id=>3, :client_id=>1, :promoter_id=>6, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>2, :promoter_id=>6, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>3, :promoter_id=>6, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>16, :promoter_id=>6, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>41, :promoter_id=>6, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>37, :promoter_id=>6, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>23, :promoter_id=>6, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>51, :promoter_id=>6, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>99, :promoter_id=>6, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>199, :promoter_id=>6, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>14, :promoter_id=>6, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>131, :promoter_id=>6, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>122, :promoter_id=>6, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>10, :promoter_id=>6, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>145, :promoter_id=>6, :event_price_id=>9, :reason=>"Good boy!")

# tickets for third event by 5th promoter
Ticket.create(:event_id=>3, :client_id=>1, :promoter_id=>7, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>2, :promoter_id=>7, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>3, :promoter_id=>7, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>15, :promoter_id=>7, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>124, :promoter_id=>7, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>127, :promoter_id=>7, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>142, :promoter_id=>7, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>166, :promoter_id=>7, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>175, :promoter_id=>7, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>186, :promoter_id=>7, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>191, :promoter_id=>7, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>149, :promoter_id=>7, :event_price_id=>9, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>194, :promoter_id=>7, :event_price_id=>7, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>130, :promoter_id=>7, :event_price_id=>8, :reason=>"Good boy!")
Ticket.create(:event_id=>3, :client_id=>177, :promoter_id=>7, :event_price_id=>9, :reason=>"Good boy!")
