# Production
Production.create(:name=>"Awesome Line")

# producers
User.create(:production_id=>1, :first_name=>"Edgar", :last_name=>"Norris", :email=>"producer1@1.com" ,:password=>"12345678", :phone_number=>"0541119111", :role=>"producer", :lock=>false)
User.create(:production_id=>1, :first_name=>"Jony", :last_name=>"Beck", :email=>"producer2@1.com" ,:password=>"12345678", :phone_number=>"0541111112", :role=>"producer", :lock=>false)

# promoters
User.create(:production_id=>1, :first_name=>"Harmonie", :last_name=>"Diane", :email=>"promoter1@1.com" ,:password=>"12345678", :role=>"promoter", :lock=>false)
User.create(:production_id=>1, :first_name=>"Diana", :last_name=>"Burke", :email=>"promoter2@1.com" ,:password=>"12345678", :role=>"promoter", :lock=>false)
User.create(:production_id=>1, :first_name=>"Melanie", :last_name=>"Jensen", :email=>"promoter3@1.com" ,:password=>"12345678", :role=>"promoter", :lock=>false)

# cashiers
User.create(:production_id=>1, :first_name=>"Victoria", :last_name=>"Watson", :email=>"cashier1@1.com" ,:password=>"12345678", :role=>"cashier", :lock=>false)
User.create(:production_id=>1, :first_name=>"Orville", :last_name=>"Burke", :email=>"cashier2@1.com" ,:password=>"12345678", :role=>"cashier", :lock=>false)

# lock users
User.create(:production_id=>1, :first_name=>"Rose", :last_name=>"Harper", :email=>"lock2@1.com" ,:password=>"12345678", :phone_number=>"0544111111", :role=>"promoter", :lock=>true)
User.create(:production_id=>1, :first_name=>"Shari", :last_name=>"Scott", :email=>"lock3@1.com" ,:password=>"12345678", :phone_number=>"0541111111", :role=>"cashier", :lock=>true)

# clients
Client.create(:production_id=>1 ,:first_name=>"Alex", :last_name=>"Hunt", :gender=>"male", :phone_number=>"0501111111", :city =>"Tel Mond", :birthdate=>"1997-05-21")
Client.create(:production_id=>1 ,:first_name=>"Leland", :last_name=>"Willis", :gender=>"female", :phone_number=>"0502111111", :city =>"Tel Mond", :birthdate=>"1997-05-22")
Client.create(:production_id=>1 ,:first_name=>"Luther", :last_name=>"Barnes", :gender=>"male", :phone_number=>"0503111111", :city =>"Tel Mond", :birthdate=>"1997-05-23")
Client.create(:production_id=>1 ,:first_name=>"Donnie", :last_name=>"Hill", :gender=>"female", :phone_number=>"0504111111", :city =>"Tel Mond", :birthdate=>"1997-05-24")
Client.create(:production_id=>1 ,:first_name=>"Christopher", :last_name=>"Mann", :gender=>"male", :phone_number=>"0505111111", :city =>"Tel Mond", :birthdate=>"1997-05-25")
Client.create(:production_id=>1 ,:first_name=>"Paul", :last_name=>"Mccarthy", :gender=>"female", :phone_number=>"0506111111", :city =>"Tel Mond", :birthdate=>"1997-05-26")
Client.create(:production_id=>1 ,:first_name=>"Bob", :last_name=>"Valdez", :gender=>"male", :phone_number=>"0507111111", :city =>"Tel Mond", :birthdate=>"1997-05-27")
Client.create(:production_id=>1 ,:first_name=>"Robin", :last_name=>"Neal", :gender=>"female", :phone_number=>"0508111111", :city =>"Tel Mond", :birthdate=>"1997-05-28")
Client.create(:production_id=>1 ,:first_name=>"Dana", :last_name=>"Parks", :gender=>"male", :phone_number=>"0509111111", :city =>"Tel Mond", :birthdate=>"1997-05-29")
Client.create(:production_id=>1 ,:first_name=>"Sam", :last_name=>"Gilbert", :gender=>"female", :phone_number=>"0500111111", :city =>"Tel Mond", :birthdate=>"1997-05-08")
Client.create(:production_id=>1 ,:first_name=>"Ted", :last_name=>"Wilkins", :gender=>"male", :phone_number=>"0301111111", :city =>"Tel Aviv", :birthdate=>"1997-06-21")
Client.create(:production_id=>1 ,:first_name=>"Rene", :last_name=>"Frazier", :gender=>"female", :phone_number=>"0501211111", :city =>"Tel Aviv", :birthdate=>"1997-06-22")
Client.create(:production_id=>1 ,:first_name=>"Darin", :last_name=>"Daniels", :gender=>"male", :phone_number=>"0501311111", :city =>"Tel Aviv", :birthdate=>"1997-06-23")
Client.create(:production_id=>1 ,:first_name=>"Phillip", :last_name=>"Cummings", :gender=>"female", :phone_number=>"0501411111", :city =>"Tel Aviv", :birthdate=>"1997-06-24")
Client.create(:production_id=>1 ,:first_name=>"Marcus", :last_name=>"Austin", :gender=>"male", :phone_number=>"0501511111", :city =>"Tel Aviv", :birthdate=>"1997-06-25")
Client.create(:production_id=>1 ,:first_name=>"Hector", :last_name=>"Sparks", :gender=>"female", :phone_number=>"0501611111", :city =>"Tel Aviv", :birthdate=>"1997-06-26")
Client.create(:production_id=>1 ,:first_name=>"Eric", :last_name=>"Bell", :gender=>"male", :phone_number=>"0501811111", :city =>"Tel Aviv", :birthdate=>"1997-06-28")
Client.create(:production_id=>1 ,:first_name=>"Lester", :last_name=>"Erickson", :gender=>"female", :phone_number=>"0501911111", :city =>"Tel Aviv", :birthdate=>"1997-06-29")
Client.create(:production_id=>1 ,:first_name=>"Bennie", :last_name=>"Hernandez", :gender=>"male", :phone_number=>"0501011111", :city =>"Tel Aviv", :birthdate=>"1997-06-20")
Client.create(:production_id=>1 ,:first_name=>"Damon", :last_name=>"Warren", :gender=>"female", :phone_number=>"0501121111", :city =>"Ramat Gan", :birthdate=>"1997-07-20")
Client.create(:production_id=>1 ,:first_name=>"Blake", :last_name=>"Mcdaniel", :gender=>"male", :phone_number=>"0501131111", :city =>"Ramat Gan", :birthdate=>"1997-07-21")
Client.create(:production_id=>1 ,:first_name=>"Tomas", :last_name=>"Strickland", :gender=>"female", :phone_number=>"0501141111", :city =>"Ramat Gan", :birthdate=>"1997-07-22")
Client.create(:production_id=>1 ,:first_name=>"Howard", :last_name=>"Delgado", :gender=>"male", :phone_number=>"0501151111", :city =>"Ramat Gan", :birthdate=>"1997-07-23")
Client.create(:production_id=>1 ,:first_name=>"Dominic", :last_name=>"James", :gender=>"female", :phone_number=>"0501161111", :city =>"Ramat Gan", :birthdate=>"1997-07-24")
Client.create(:production_id=>1 ,:first_name=>"Seth", :last_name=>"Hughes", :gender=>"male", :phone_number=>"0501171111", :city =>"Ramat Gan", :birthdate=>"1997-07-25")
Client.create(:production_id=>1 ,:first_name=>"Ashley", :last_name=>"James", :gender=>"female", :phone_number=>"0521161111", :city =>"Ramat Gan", :birthdate=>"1997-07-24")
Client.create(:production_id=>1 ,:first_name=>"Dorothy", :last_name=>"Hughes", :gender=>"male", :phone_number=>"0521171111", :city =>"Ramat Gan", :birthdate=>"1997-07-25")
Client.create(:production_id=>1 ,:first_name=>"Gloria", :last_name=>"Bowers", :gender=>"female", :phone_number=>"0521181111", :city =>"Ramat Gan", :birthdate=>"1997-07-26")
Client.create(:production_id=>1 ,:first_name=>"Jane", :last_name=>"Doyle", :gender=>"male", :phone_number=>"0521191111", :city =>"Ramat Gan", :birthdate=>"1997-07-27")
Client.create(:production_id=>1 ,:first_name=>"Brenda", :last_name=>"Morris", :gender=>"female", :phone_number=>"0521101111", :city =>"Ramat Gan", :birthdate=>"1997-07-28")
Client.create(:production_id=>1 ,:first_name=>"Janet", :last_name=>"Lawson", :gender=>"male", :phone_number=>"0521111111", :city =>"Ramat Gan", :birthdate=>"1997-07-29")
Client.create(:production_id=>1 ,:first_name=>"Emily", :last_name=>"Taylor", :gender=>"female", :phone_number=>"0521111111", :city =>"Raanana", :birthdate=>"1997-08-20")
Client.create(:production_id=>1 ,:first_name=>"Janice", :last_name=>"Wong", :gender=>"male", :phone_number=>"0521112111", :city =>"Raanana", :birthdate=>"1997-08-21")
Client.create(:production_id=>1 ,:first_name=>"Sharon", :last_name=>"Blake", :gender=>"female", :phone_number=>"0521113111", :city =>"Raanana", :birthdate=>"1997-08-22")
Client.create(:production_id=>1 ,:first_name=>"Marie", :last_name=>"May", :gender=>"male", :phone_number=>"0521114111", :city =>"Raanana", :birthdate=>"1997-08-23")
Client.create(:production_id=>1 ,:first_name=>"Irene", :last_name=>"Roberson", :gender=>"female", :phone_number=>"0521115111", :city =>"Raanana", :birthdate=>"1997-08-24")
Client.create(:production_id=>1 ,:first_name=>"Mary", :last_name=>"King", :gender=>"male", :phone_number=>"0521116111", :city =>"Raanana", :birthdate=>"1997-08-25")
Client.create(:production_id=>1 ,:first_name=>"Betty", :last_name=>"Mckinney", :gender=>"female", :phone_number=>"0521117111", :city =>"Raanana", :birthdate=>"1997-08-26")
Client.create(:production_id=>1 ,:first_name=>"Phyllis", :last_name=>"Lyons", :gender=>"male", :phone_number=>"0521118111", :city =>"Raanana", :birthdate=>"1997-08-27")
Client.create(:production_id=>1 ,:first_name=>"Helen", :last_name=>"Lucas", :gender=>"female", :phone_number=>"0521119111", :city =>"Raanana", :birthdate=>"1997-08-28")
Client.create(:production_id=>1 ,:first_name=>"Martha", :last_name=>"Greene", :gender=>"male", :phone_number=>"0521110111", :city =>"Raanana", :birthdate=>"1997-08-29")
Client.create(:production_id=>1 ,:first_name=>"Cheryl", :last_name=>"Wolfe", :gender=>"female", :phone_number=>"0521111111", :city =>"Kfar Sava", :birthdate=>"1997-09-20")
Client.create(:production_id=>1 ,:first_name=>"Patricia", :last_name=>"Underwood", :gender=>"male", :phone_number=>"0521111211", :city =>"Kfar Sava", :birthdate=>"1997-09-21")
Client.create(:production_id=>1 ,:first_name=>"Michelle", :last_name=>"Page", :gender=>"female", :phone_number=>"0521111311", :city =>"Kfar Sava", :birthdate=>"1997-09-22")
Client.create(:production_id=>1 ,:first_name=>"Lori", :last_name=>"Murray", :gender=>"male", :phone_number=>"0521111411", :city =>"Kfar Sava", :birthdate=>"1997-09-23")
Client.create(:production_id=>1 ,:first_name=>"Pamela", :last_name=>"Lynch", :gender=>"female", :phone_number=>"0521111511", :city =>"Kfar Sava", :birthdate=>"1997-09-24")
Client.create(:production_id=>1 ,:first_name=>"Andrea", :last_name=>"Guerrero", :gender=>"male", :phone_number=>"0521111611", :city =>"Kfar Sava", :birthdate=>"1997-09-25")
Client.create(:production_id=>1 ,:first_name=>"Christine", :last_name=>"Evans", :gender=>"female", :phone_number=>"0521111711", :city =>"Kfar Sava", :birthdate=>"1997-09-26")
Client.create(:production_id=>1 ,:first_name=>"Katherine", :last_name=>"Wallace", :gender=>"male", :phone_number=>"0521111811", :city =>"Kfar Sava", :birthdate=>"1997-09-27")
Client.create(:production_id=>1 ,:first_name=>"Catherine", :last_name=>"French", :gender=>"female", :phone_number=>"0521111911", :city =>"Kfar Sava", :birthdate=>"1997-09-28")
Client.create(:production_id=>1 ,:first_name=>"Elizabeth", :last_name=>"Wong", :gender=>"female", :phone_number=>"0421362111", :city =>"Raanana", :birthdate=>"1997-08-21")
Client.create(:production_id=>1 ,:first_name=>"Tammy", :last_name=>"Blake", :gender=>"female", :phone_number=>"0721613780", :city =>"Raanana", :birthdate=>"1997-08-22")

# events
Event.create(:production_id=>1, :user_id=>1, :name=>"Amsterdam Open Air", :when=>DateTime.now - 30*4)
Event.create(:production_id=>1, :user_id=>2, :name=>"Tomorrowland", :when=>DateTime.now - 30*3)
Event.create(:production_id=>1, :user_id=>1, :name=>"Muzix", :when=>DateTime.now - 30*2)
Event.create(:production_id=>1, :user_id=>2, :name=>"Sound Of Sunset", :when=>DateTime.now - 30)
Event.create(:production_id=>1, :user_id=>1, :name=>"Color Festival", :when=>DateTime.now)
Event.create(:production_id=>1, :user_id=>2, :name=>"Friends Party", :when=>DateTime.now + 30)

# prices for events
EventPrice.create(:event_id=>1, :price=>"0")
EventPrice.create(:event_id=>1, :price=>"5")
EventPrice.create(:event_id=>1, :price=>"10")
EventPrice.create(:event_id=>1, :price=>"15")
EventPrice.create(:event_id=>2, :price=>"0")
EventPrice.create(:event_id=>2, :price=>"5")
EventPrice.create(:event_id=>2, :price=>"10")
EventPrice.create(:event_id=>2, :price=>"15")
EventPrice.create(:event_id=>3, :price=>"0")
EventPrice.create(:event_id=>3, :price=>"5")
EventPrice.create(:event_id=>3, :price=>"10")
EventPrice.create(:event_id=>3, :price=>"15")
EventPrice.create(:event_id=>4, :price=>"0")
EventPrice.create(:event_id=>4, :price=>"5")
EventPrice.create(:event_id=>4, :price=>"10")
EventPrice.create(:event_id=>4, :price=>"15")
EventPrice.create(:event_id=>5, :price=>"0")
EventPrice.create(:event_id=>5, :price=>"5")
EventPrice.create(:event_id=>5, :price=>"10")
EventPrice.create(:event_id=>5, :price=>"15")
EventPrice.create(:event_id=>6, :price=>"0")
EventPrice.create(:event_id=>6, :price=>"5")
EventPrice.create(:event_id=>6, :price=>"10")
EventPrice.create(:event_id=>6, :price=>"15")

# tickets for first event (arrived)
Ticket.create(:event_id=>1, :client_id=>1, :promoter_id=>3, :event_price_id=>1, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>1, :client_id=>2, :promoter_id=>4, :event_price_id=>2, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>1, :client_id=>3, :promoter_id=>5, :event_price_id=>3, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>1, :client_id=>4, :promoter_id=>3, :event_price_id=>1, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>1, :client_id=>5, :promoter_id=>4, :event_price_id=>4, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>1, :client_id=>6, :promoter_id=>5, :event_price_id=>3, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>1, :client_id=>7, :promoter_id=>3, :event_price_id=>1, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>1, :client_id=>8, :promoter_id=>4, :event_price_id=>2, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>1, :client_id=>9, :promoter_id=>5, :event_price_id=>3, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>1, :client_id=>11, :promoter_id=>3, :event_price_id=>1, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>1, :client_id=>12, :promoter_id=>4, :event_price_id=>4, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>1, :client_id=>14, :promoter_id=>5, :event_price_id=>3, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>1, :client_id=>15, :promoter_id=>3, :event_price_id=>1, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>1, :client_id=>16, :promoter_id=>4, :event_price_id=>2, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>1, :client_id=>17, :promoter_id=>5, :event_price_id=>3, :arrived=>true, :cashier_id=>7)

# tickets for first event (did not arrived)
Ticket.create(:event_id=>1, :client_id=>1, :promoter_id=>4, :event_price_id=>4, :arrived=>false)
Ticket.create(:event_id=>1, :client_id=>2, :promoter_id=>5, :event_price_id=>3, :arrived=>false)
Ticket.create(:event_id=>1, :client_id=>7, :promoter_id=>4, :event_price_id=>2, :arrived=>false)
Ticket.create(:event_id=>1, :client_id=>20, :promoter_id=>3, :event_price_id=>4, :arrived=>false)
Ticket.create(:event_id=>1, :client_id=>22, :promoter_id=>5, :event_price_id=>3, :arrived=>false)
Ticket.create(:event_id=>1, :client_id=>23, :promoter_id=>4, :event_price_id=>2, :arrived=>false)
Ticket.create(:event_id=>1, :client_id=>24, :promoter_id=>3, :event_price_id=>4, :arrived=>false)
Ticket.create(:event_id=>1, :client_id=>25, :promoter_id=>5, :event_price_id=>3, :arrived=>false)
Ticket.create(:event_id=>1, :client_id=>26, :promoter_id=>4, :event_price_id=>2, :arrived=>false)

# tickets for second event (arrived)
Ticket.create(:event_id=>2, :client_id=>22, :promoter_id=>3, :event_price_id=>5, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>2, :client_id=>23, :promoter_id=>3, :event_price_id=>5, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>2, :client_id=>24, :promoter_id=>4, :event_price_id=>6, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>25, :promoter_id=>5, :event_price_id=>7, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>26, :promoter_id=>4, :event_price_id=>8, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>27, :promoter_id=>4, :event_price_id=>6, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>28, :promoter_id=>5, :event_price_id=>7, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>29, :promoter_id=>4, :event_price_id=>8, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>30, :promoter_id=>3, :event_price_id=>5, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>2, :client_id=>31, :promoter_id=>4, :event_price_id=>6, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>34, :promoter_id=>5, :event_price_id=>7, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>35, :promoter_id=>4, :event_price_id=>8, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>36, :promoter_id=>3, :event_price_id=>5, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>2, :client_id=>37, :promoter_id=>4, :event_price_id=>6, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>38, :promoter_id=>5, :event_price_id=>7, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>39, :promoter_id=>5, :event_price_id=>7, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>43, :promoter_id=>4, :event_price_id=>8, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>2, :client_id=>44, :promoter_id=>4, :event_price_id=>8, :arrived=>true, :cashier_id=>7)

# tickets for second event (did not arrived)
Ticket.create(:event_id=>2, :client_id=>22, :promoter_id=>4, :event_price_id=>8, :arrived=>false)
Ticket.create(:event_id=>2, :client_id=>23, :promoter_id=>5, :event_price_id=>7, :arrived=>false)
Ticket.create(:event_id=>2, :client_id=>36, :promoter_id=>4, :event_price_id=>6, :arrived=>false)
Ticket.create(:event_id=>2, :client_id=>1, :promoter_id=>3, :event_price_id=>8, :arrived=>false)
Ticket.create(:event_id=>2, :client_id=>2, :promoter_id=>4, :event_price_id=>8, :arrived=>false)
Ticket.create(:event_id=>2, :client_id=>3, :promoter_id=>5, :event_price_id=>7, :arrived=>false)
Ticket.create(:event_id=>2, :client_id=>4, :promoter_id=>3, :event_price_id=>6, :arrived=>false)
Ticket.create(:event_id=>2, :client_id=>5, :promoter_id=>3, :event_price_id=>8, :arrived=>false)

# tickets for third event (arrived)
Ticket.create(:event_id=>3, :client_id=>50, :promoter_id=>3, :event_price_id=>9, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>3, :client_id=>49, :promoter_id=>4, :event_price_id=>10, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>3, :client_id=>48, :promoter_id=>4, :event_price_id=>11, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>3, :client_id=>47, :promoter_id=>5, :event_price_id=>12, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>3, :client_id=>46, :promoter_id=>3, :event_price_id=>9, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>3, :client_id=>45, :promoter_id=>4, :event_price_id=>10, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>3, :client_id=>44, :promoter_id=>4, :event_price_id=>11, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>3, :client_id=>43, :promoter_id=>5, :event_price_id=>12, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>3, :client_id=>42, :promoter_id=>3, :event_price_id=>9, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>3, :client_id=>41, :promoter_id=>4, :event_price_id=>10, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>3, :client_id=>40, :promoter_id=>4, :event_price_id=>11, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>3, :client_id=>39, :promoter_id=>5, :event_price_id=>12, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>3, :client_id=>38, :promoter_id=>3, :event_price_id=>9, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>3, :client_id=>37, :promoter_id=>4, :event_price_id=>10, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>3, :client_id=>36, :promoter_id=>4, :event_price_id=>11, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>3, :client_id=>35, :promoter_id=>5, :event_price_id=>12, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>3, :client_id=>34, :promoter_id=>5, :event_price_id=>12, :arrived=>true, :cashier_id=>7)

# tickets for third event (did not arrived)
Ticket.create(:event_id=>3, :client_id=>50, :promoter_id=>4, :event_price_id=>12, :arrived=>false)
Ticket.create(:event_id=>3, :client_id=>49, :promoter_id=>3, :event_price_id=>11, :arrived=>false)
Ticket.create(:event_id=>3, :client_id=>48, :promoter_id=>5, :event_price_id=>11, :arrived=>false)
Ticket.create(:event_id=>3, :client_id=>21, :promoter_id=>4, :event_price_id=>12, :arrived=>false)
Ticket.create(:event_id=>3, :client_id=>22, :promoter_id=>3, :event_price_id=>11, :arrived=>false)
Ticket.create(:event_id=>3, :client_id=>23, :promoter_id=>5, :event_price_id=>11, :arrived=>false)

# tickets for 4th event (arrived)
Ticket.create(:event_id=>4, :client_id=>11, :promoter_id=>3, :event_price_id=>13, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>4, :client_id=>12, :promoter_id=>4, :event_price_id=>14, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>13, :promoter_id=>5, :event_price_id=>15, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>4, :client_id=>14, :promoter_id=>3, :event_price_id=>16, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>15, :promoter_id=>3, :event_price_id=>13, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>4, :client_id=>16, :promoter_id=>4, :event_price_id=>14, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>17, :promoter_id=>5, :event_price_id=>15, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>4, :client_id=>18, :promoter_id=>3, :event_price_id=>16, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>19, :promoter_id=>3, :event_price_id=>13, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>4, :client_id=>20, :promoter_id=>4, :event_price_id=>14, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>1, :promoter_id=>5, :event_price_id=>15, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>4, :client_id=>2, :promoter_id=>3, :event_price_id=>16, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>3, :promoter_id=>3, :event_price_id=>16, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>4, :promoter_id=>3, :event_price_id=>16, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>5, :promoter_id=>3, :event_price_id=>13, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>4, :client_id=>6, :promoter_id=>4, :event_price_id=>14, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>7, :promoter_id=>5, :event_price_id=>15, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>4, :client_id=>8, :promoter_id=>3, :event_price_id=>16, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>4, :client_id=>9, :promoter_id=>3, :event_price_id=>13, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>4, :client_id=>10, :promoter_id=>4, :event_price_id=>14, :arrived=>true, :cashier_id=>7)

# tickets for 4th event (did not arrived)
Ticket.create(:event_id=>4, :client_id=>12, :promoter_id=>3, :event_price_id=>16, :arrived=>false)
Ticket.create(:event_id=>4, :client_id=>11, :promoter_id=>4, :event_price_id=>16, :arrived=>false)
Ticket.create(:event_id=>4, :client_id=>16, :promoter_id=>5, :event_price_id=>16, :arrived=>false)
Ticket.create(:event_id=>4, :client_id=>31, :promoter_id=>3, :event_price_id=>16, :arrived=>false)
Ticket.create(:event_id=>4, :client_id=>32, :promoter_id=>4, :event_price_id=>16, :arrived=>false)
Ticket.create(:event_id=>4, :client_id=>33, :promoter_id=>5, :event_price_id=>16, :arrived=>false)


# tickets for 5th event (arrived)
Ticket.create(:event_id=>5, :client_id=>27, :promoter_id=>3, :event_price_id=>17, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>5, :client_id=>28, :promoter_id=>4, :event_price_id=>18, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>5, :client_id=>29, :promoter_id=>5, :event_price_id=>19, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>5, :client_id=>30, :promoter_id=>5, :event_price_id=>20, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>5, :client_id=>31, :promoter_id=>3, :event_price_id=>17, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>5, :client_id=>32, :promoter_id=>4, :event_price_id=>18, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>5, :client_id=>33, :promoter_id=>5, :event_price_id=>19, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>5, :client_id=>21, :promoter_id=>5, :event_price_id=>20, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>5, :client_id=>22, :promoter_id=>3, :event_price_id=>17, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>5, :client_id=>23, :promoter_id=>4, :event_price_id=>18, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>5, :client_id=>24, :promoter_id=>5, :event_price_id=>19, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>5, :client_id=>13, :promoter_id=>5, :event_price_id=>20, :arrived=>true, :cashier_id=>7)
Ticket.create(:event_id=>5, :client_id=>14, :promoter_id=>3, :event_price_id=>17, :arrived=>true, :cashier_id=>6)
Ticket.create(:event_id=>5, :client_id=>15, :promoter_id=>4, :event_price_id=>18, :arrived=>true, :cashier_id=>7)

# tickets for 5th event (did not arrived)
Ticket.create(:event_id=>5, :client_id=>29, :promoter_id=>3, :event_price_id=>20, :arrived=>false)
Ticket.create(:event_id=>5, :client_id=>27, :promoter_id=>4, :event_price_id=>20, :arrived=>false)
Ticket.create(:event_id=>5, :client_id=>28, :promoter_id=>5, :event_price_id=>19, :arrived=>false)
Ticket.create(:event_id=>5, :client_id=>15, :promoter_id=>3, :event_price_id=>20, :arrived=>false)
Ticket.create(:event_id=>5, :client_id=>1, :promoter_id=>4, :event_price_id=>19, :arrived=>false)
Ticket.create(:event_id=>5, :client_id=>2, :promoter_id=>5, :event_price_id=>20, :arrived=>false)

# tickets for 6th event (future event)
Ticket.create(:event_id=>6, :client_id=>26, :promoter_id=>3, :event_price_id=>21)
Ticket.create(:event_id=>6, :client_id=>27, :promoter_id=>4, :event_price_id=>22)
Ticket.create(:event_id=>6, :client_id=>28, :promoter_id=>4, :event_price_id=>23)
Ticket.create(:event_id=>6, :client_id=>34, :promoter_id=>5, :event_price_id=>24)
Ticket.create(:event_id=>6, :client_id=>36, :promoter_id=>3, :event_price_id=>24)
Ticket.create(:event_id=>6, :client_id=>37, :promoter_id=>5, :event_price_id=>21)
Ticket.create(:event_id=>6, :client_id=>38, :promoter_id=>5, :event_price_id=>22)
Ticket.create(:event_id=>6, :client_id=>39, :promoter_id=>4, :event_price_id=>23)
Ticket.create(:event_id=>6, :client_id=>49, :promoter_id=>3, :event_price_id=>24)
Ticket.create(:event_id=>6, :client_id=>50, :promoter_id=>5, :event_price_id=>24)
# Ticket.create(:event_id=>6, :client_id=>29, :promoter_id=>3, :event_price_id=>24)
# Ticket.create(:event_id=>6, :client_id=>30, :promoter_id=>5, :event_price_id=>24)
# Ticket.create(:event_id=>6, :client_id=>31, :promoter_id=>3, :event_price_id=>24)

# comments
ClientComment.create(:user_id=>3, :client_id=>1, :comment=>"Nice man.")
ClientComment.create(:user_id=>4, :client_id=>1, :comment=>"Highly recommended.")
ClientComment.create(:user_id=>5, :client_id=>1, :comment=>"Plesure.")
ClientComment.create(:user_id=>3, :client_id=>2, :comment=>"Nice man.")
ClientComment.create(:user_id=>4, :client_id=>2, :comment=>"Highly recommended.")
ClientComment.create(:user_id=>5, :client_id=>2, :comment=>"Plesure.")
ClientComment.create(:user_id=>3, :client_id=>3, :comment=>"Nice man.")
ClientComment.create(:user_id=>4, :client_id=>3, :comment=>"Highly recommended.")
ClientComment.create(:user_id=>5, :client_id=>3, :comment=>"Plesure.")
ClientComment.create(:user_id=>3, :client_id=>4, :comment=>"Nice man.")
ClientComment.create(:user_id=>4, :client_id=>4, :comment=>"Highly recommended.")
ClientComment.create(:user_id=>5, :client_id=>4, :comment=>"Plesure.")
ClientComment.create(:user_id=>3, :client_id=>5, :comment=>"Nice man.")
ClientComment.create(:user_id=>4, :client_id=>5, :comment=>"Highly recommended.")
ClientComment.create(:user_id=>5, :client_id=>5, :comment=>"Plesure.")
ClientComment.create(:user_id=>3, :client_id=>6, :comment=>"Your average senior superlatives are boring, banal, and woefully inadequate for honoring the myriad skills and talents of your class.")
ClientComment.create(:user_id=>4, :client_id=>7, :comment=>"Best Epidermis.")
ClientComment.create(:user_id=>5, :client_id=>8, :comment=>"Most Bacon-y Smelling Armpits.")
ClientComment.create(:user_id=>3, :client_id=>9, :comment=>"Smoothest Tongue.")
ClientComment.create(:user_id=>4, :client_id=>10, :comment=>"Your average senior superlatives are boring, banal, and woefully inadequate for honoring the myriad skills and talents of your class.")
ClientComment.create(:user_id=>5, :client_id=>11, :comment=>"Smoothest Tongue.")
ClientComment.create(:user_id=>3, :client_id=>12, :comment=>"Best Epidermis.")
ClientComment.create(:user_id=>4, :client_id=>13, :comment=>"Most Bacon-y Smelling Armpits.")
ClientComment.create(:user_id=>5, :client_id=>14, :comment=>"Smoothest Tongue.")
ClientComment.create(:user_id=>3, :client_id=>15, :comment=>"Your average senior superlatives are boring, banal, and woefully inadequate for honoring the myriad skills and talents of your class.")
ClientComment.create(:user_id=>4, :client_id=>16, :comment=>"Twitchiest Eyebrow.")
ClientComment.create(:user_id=>5, :client_id=>17, :comment=>"Twitchiest Eyebrow.")
ClientComment.create(:user_id=>3, :client_id=>18, :comment=>"Twitchiest Eyebrow.")
ClientComment.create(:user_id=>4, :client_id=>19, :comment=>"Most Bacon-y Smelling Armpits.")
ClientComment.create(:user_id=>5, :client_id=>20, :comment=>"Best Epidermis.")
ClientComment.create(:user_id=>3, :client_id=>21, :comment=>"Prettiest Thighs.")
ClientComment.create(:user_id=>4, :client_id=>22, :comment=>"Prettiest Thighs.")
ClientComment.create(:user_id=>5, :client_id=>23, :comment=>"Best Epidermis.")
ClientComment.create(:user_id=>3, :client_id=>24, :comment=>"Prettiest Thighs.")
ClientComment.create(:user_id=>4, :client_id=>25, :comment=>"Prettiest Thighs.")

# friendships
ClientFriendship.create(:user_id=>3, :client_one_id=>1, :client_two_id=>2)
ClientFriendship.create(:user_id=>4, :client_one_id=>1, :client_two_id=>3)
ClientFriendship.create(:user_id=>5, :client_one_id=>1, :client_two_id=>4)
ClientFriendship.create(:user_id=>3, :client_one_id=>1, :client_two_id=>5)
ClientFriendship.create(:user_id=>3, :client_one_id=>2, :client_two_id=>3)
ClientFriendship.create(:user_id=>4, :client_one_id=>2, :client_two_id=>4)
ClientFriendship.create(:user_id=>5, :client_one_id=>2, :client_two_id=>5)
ClientFriendship.create(:user_id=>4, :client_one_id=>3, :client_two_id=>4)
ClientFriendship.create(:user_id=>5, :client_one_id=>3, :client_two_id=>5)
ClientFriendship.create(:user_id=>3, :client_one_id=>4, :client_two_id=>5)

ClientFriendship.create(:user_id=>3, :client_one_id=>6, :client_two_id=>7)
ClientFriendship.create(:user_id=>4, :client_one_id=>6, :client_two_id=>8)
ClientFriendship.create(:user_id=>5, :client_one_id=>6, :client_two_id=>9)
ClientFriendship.create(:user_id=>3, :client_one_id=>6, :client_two_id=>10)
ClientFriendship.create(:user_id=>4, :client_one_id=>7, :client_two_id=>8)
ClientFriendship.create(:user_id=>5, :client_one_id=>7, :client_two_id=>9)
ClientFriendship.create(:user_id=>3, :client_one_id=>7, :client_two_id=>10)
ClientFriendship.create(:user_id=>5, :client_one_id=>8, :client_two_id=>9)
ClientFriendship.create(:user_id=>3, :client_one_id=>8, :client_two_id=>10)
ClientFriendship.create(:user_id=>3, :client_one_id=>9, :client_two_id=>10)

ClientFriendship.create(:user_id=>3, :client_one_id=>11, :client_two_id=>12)
ClientFriendship.create(:user_id=>4, :client_one_id=>11, :client_two_id=>13)
ClientFriendship.create(:user_id=>3, :client_one_id=>11, :client_two_id=>14)
ClientFriendship.create(:user_id=>5, :client_one_id=>11, :client_two_id=>15)
ClientFriendship.create(:user_id=>4, :client_one_id=>12, :client_two_id=>13)
ClientFriendship.create(:user_id=>3, :client_one_id=>12, :client_two_id=>14)
ClientFriendship.create(:user_id=>5, :client_one_id=>12, :client_two_id=>15)
ClientFriendship.create(:user_id=>3, :client_one_id=>13, :client_two_id=>14)
ClientFriendship.create(:user_id=>5, :client_one_id=>13, :client_two_id=>15)
ClientFriendship.create(:user_id=>5, :client_one_id=>14, :client_two_id=>15)

ClientFriendship.create(:user_id=>5, :client_one_id=>16, :client_two_id=>17)
ClientFriendship.create(:user_id=>4, :client_one_id=>16, :client_two_id=>18)
ClientFriendship.create(:user_id=>3, :client_one_id=>16, :client_two_id=>19)
ClientFriendship.create(:user_id=>5, :client_one_id=>16, :client_two_id=>20)
ClientFriendship.create(:user_id=>4, :client_one_id=>17, :client_two_id=>18)
ClientFriendship.create(:user_id=>3, :client_one_id=>17, :client_two_id=>19)
ClientFriendship.create(:user_id=>5, :client_one_id=>17, :client_two_id=>20)
ClientFriendship.create(:user_id=>3, :client_one_id=>18, :client_two_id=>19)
ClientFriendship.create(:user_id=>5, :client_one_id=>18, :client_two_id=>20)
ClientFriendship.create(:user_id=>5, :client_one_id=>19, :client_two_id=>20)

ClientFriendship.create(:user_id=>5, :client_one_id=>21, :client_two_id=>22)
ClientFriendship.create(:user_id=>4, :client_one_id=>21, :client_two_id=>23)
ClientFriendship.create(:user_id=>3, :client_one_id=>21, :client_two_id=>24)
ClientFriendship.create(:user_id=>5, :client_one_id=>21, :client_two_id=>25)
ClientFriendship.create(:user_id=>4, :client_one_id=>22, :client_two_id=>23)
ClientFriendship.create(:user_id=>3, :client_one_id=>22, :client_two_id=>24)
ClientFriendship.create(:user_id=>5, :client_one_id=>22, :client_two_id=>25)
ClientFriendship.create(:user_id=>3, :client_one_id=>23, :client_two_id=>24)
ClientFriendship.create(:user_id=>5, :client_one_id=>23, :client_two_id=>25)
ClientFriendship.create(:user_id=>5, :client_one_id=>24, :client_two_id=>25)

ClientFriendship.create(:user_id=>5, :client_one_id=>26, :client_two_id=>27)
ClientFriendship.create(:user_id=>4, :client_one_id=>26, :client_two_id=>28)
ClientFriendship.create(:user_id=>3, :client_one_id=>26, :client_two_id=>29)
ClientFriendship.create(:user_id=>5, :client_one_id=>26, :client_two_id=>30)
ClientFriendship.create(:user_id=>4, :client_one_id=>26, :client_two_id=>31)
ClientFriendship.create(:user_id=>3, :client_one_id=>26, :client_two_id=>32)
ClientFriendship.create(:user_id=>3, :client_one_id=>26, :client_two_id=>33)
ClientFriendship.create(:user_id=>4, :client_one_id=>27, :client_two_id=>28)
ClientFriendship.create(:user_id=>3, :client_one_id=>27, :client_two_id=>29)
ClientFriendship.create(:user_id=>5, :client_one_id=>27, :client_two_id=>30)
ClientFriendship.create(:user_id=>4, :client_one_id=>27, :client_two_id=>31)
ClientFriendship.create(:user_id=>3, :client_one_id=>27, :client_two_id=>32)
ClientFriendship.create(:user_id=>3, :client_one_id=>27, :client_two_id=>33)
ClientFriendship.create(:user_id=>3, :client_one_id=>28, :client_two_id=>29)
ClientFriendship.create(:user_id=>5, :client_one_id=>28, :client_two_id=>30)
ClientFriendship.create(:user_id=>4, :client_one_id=>28, :client_two_id=>31)
ClientFriendship.create(:user_id=>3, :client_one_id=>28, :client_two_id=>32)
ClientFriendship.create(:user_id=>3, :client_one_id=>28, :client_two_id=>33)
ClientFriendship.create(:user_id=>5, :client_one_id=>29, :client_two_id=>30)
ClientFriendship.create(:user_id=>4, :client_one_id=>29, :client_two_id=>31)
ClientFriendship.create(:user_id=>3, :client_one_id=>29, :client_two_id=>32)
ClientFriendship.create(:user_id=>3, :client_one_id=>29, :client_two_id=>33)
ClientFriendship.create(:user_id=>4, :client_one_id=>30, :client_two_id=>31)
ClientFriendship.create(:user_id=>3, :client_one_id=>30, :client_two_id=>32)
ClientFriendship.create(:user_id=>3, :client_one_id=>30, :client_two_id=>33)
ClientFriendship.create(:user_id=>3, :client_one_id=>31, :client_two_id=>32)
ClientFriendship.create(:user_id=>3, :client_one_id=>31, :client_two_id=>33)
ClientFriendship.create(:user_id=>3, :client_one_id=>32, :client_two_id=>33)

ClientFriendship.create(:user_id=>3, :client_one_id=>34, :client_two_id=>35)
ClientFriendship.create(:user_id=>4, :client_one_id=>34, :client_two_id=>36)
ClientFriendship.create(:user_id=>5, :client_one_id=>34, :client_two_id=>37)
ClientFriendship.create(:user_id=>3, :client_one_id=>34, :client_two_id=>38)
ClientFriendship.create(:user_id=>4, :client_one_id=>34, :client_two_id=>39)
ClientFriendship.create(:user_id=>5, :client_one_id=>34, :client_two_id=>40)
ClientFriendship.create(:user_id=>3, :client_one_id=>34, :client_two_id=>41)
ClientFriendship.create(:user_id=>4, :client_one_id=>34, :client_two_id=>42)
ClientFriendship.create(:user_id=>4, :client_one_id=>35, :client_two_id=>36)
ClientFriendship.create(:user_id=>5, :client_one_id=>35, :client_two_id=>37)
ClientFriendship.create(:user_id=>3, :client_one_id=>35, :client_two_id=>38)
ClientFriendship.create(:user_id=>4, :client_one_id=>35, :client_two_id=>39)
ClientFriendship.create(:user_id=>5, :client_one_id=>35, :client_two_id=>40)
ClientFriendship.create(:user_id=>3, :client_one_id=>35, :client_two_id=>41)
ClientFriendship.create(:user_id=>4, :client_one_id=>35, :client_two_id=>42)
ClientFriendship.create(:user_id=>5, :client_one_id=>36, :client_two_id=>37)
ClientFriendship.create(:user_id=>3, :client_one_id=>36, :client_two_id=>38)
ClientFriendship.create(:user_id=>4, :client_one_id=>36, :client_two_id=>39)
ClientFriendship.create(:user_id=>5, :client_one_id=>36, :client_two_id=>40)
ClientFriendship.create(:user_id=>3, :client_one_id=>36, :client_two_id=>41)
ClientFriendship.create(:user_id=>4, :client_one_id=>36, :client_two_id=>42)
ClientFriendship.create(:user_id=>3, :client_one_id=>37, :client_two_id=>38)
ClientFriendship.create(:user_id=>4, :client_one_id=>37, :client_two_id=>39)
ClientFriendship.create(:user_id=>5, :client_one_id=>37, :client_two_id=>40)
ClientFriendship.create(:user_id=>3, :client_one_id=>37, :client_two_id=>41)
ClientFriendship.create(:user_id=>4, :client_one_id=>37, :client_two_id=>42)
ClientFriendship.create(:user_id=>4, :client_one_id=>38, :client_two_id=>39)
ClientFriendship.create(:user_id=>5, :client_one_id=>38, :client_two_id=>40)
ClientFriendship.create(:user_id=>3, :client_one_id=>38, :client_two_id=>41)
ClientFriendship.create(:user_id=>4, :client_one_id=>38, :client_two_id=>42)
ClientFriendship.create(:user_id=>5, :client_one_id=>39, :client_two_id=>40)
ClientFriendship.create(:user_id=>3, :client_one_id=>39, :client_two_id=>41)
ClientFriendship.create(:user_id=>4, :client_one_id=>39, :client_two_id=>42)
ClientFriendship.create(:user_id=>3, :client_one_id=>40, :client_two_id=>41)
ClientFriendship.create(:user_id=>4, :client_one_id=>40, :client_two_id=>42)
ClientFriendship.create(:user_id=>4, :client_one_id=>41, :client_two_id=>42)

ClientFriendship.create(:user_id=>4, :client_one_id=>43, :client_two_id=>44)
ClientFriendship.create(:user_id=>3, :client_one_id=>43, :client_two_id=>45)
ClientFriendship.create(:user_id=>5, :client_one_id=>44, :client_two_id=>45)

ClientFriendship.create(:user_id=>3, :client_one_id=>46, :client_two_id=>47)
ClientFriendship.create(:user_id=>4, :client_one_id=>46, :client_two_id=>48)
ClientFriendship.create(:user_id=>5, :client_one_id=>46, :client_two_id=>49)
ClientFriendship.create(:user_id=>3, :client_one_id=>46, :client_two_id=>50)
ClientFriendship.create(:user_id=>3, :client_one_id=>47, :client_two_id=>48)
ClientFriendship.create(:user_id=>4, :client_one_id=>47, :client_two_id=>49)
ClientFriendship.create(:user_id=>5, :client_one_id=>47, :client_two_id=>50)
ClientFriendship.create(:user_id=>4, :client_one_id=>48, :client_two_id=>49)
ClientFriendship.create(:user_id=>5, :client_one_id=>48, :client_two_id=>50)
ClientFriendship.create(:user_id=>3, :client_one_id=>49, :client_two_id=>50)
